import { useState } from "react";
import type { InsightsResponse } from "../lib/types";
import { categoryLabel, formatKg } from "../lib/format";

interface Props {
  insights: InsightsResponse;
}

const CheckIcon = () => (
  <svg
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    aria-hidden="true"
  >
    <polyline points="20 6 9 17 4 12" />
  </svg>
);

/** Personalized summary + interactive, checkable reduction actions. */
export function InsightsPanel({ insights }: Props) {
  const sourceLabel = insights.source === "gemini" ? "AI-personalized" : "Smart rules";
  const [committedIndices, setCommittedIndices] = useState<Record<number, boolean>>({});

  const toggleCommit = (index: number) => {
    setCommittedIndices((prev) => ({
      ...prev,
      [index]: !prev[index],
    }));
  };

  // Calculate total savings committed by the user
  const totalCommittedSavings = insights.recommendations.reduce((sum, rec, idx) => {
    if (committedIndices[idx]) {
      return sum + rec.estimated_annual_savings_kg;
    }
    return sum;
  }, 0);

  return (
    <section className="card" aria-labelledby="insights-heading">
      <h2 id="insights-heading">
        Personalized insights{" "}
        <span className="badge" title={`Generated by: ${sourceLabel}`}>
          {sourceLabel}
        </span>
      </h2>

      <p>{insights.summary}</p>

      {totalCommittedSavings > 0 && (
        <div
          className="error"
          style={{
            borderColor: "var(--primary)",
            background: "rgba(16, 185, 129, 0.1)",
            color: "var(--text)",
            animation: "fadeIn 0.3s ease-out",
          }}
          role="status"
        >
          🌱 Committed to saving: <strong>{formatKg(totalCommittedSavings)}</strong> CO₂e / year!
        </div>
      )}

      <h3>Recommended actions</h3>
      <ul className="plain-list">
        {insights.recommendations.map((rec, i) => {
          const isCommitted = !!committedIndices[i];
          return (
            <li
              className={`recommendation ${isCommitted ? "committed" : ""}`}
              key={`${rec.category}-${i}`}
              onClick={() => toggleCommit(i)}
              style={{ cursor: "pointer" }}
            >
              <div
                className={`action-checkbox ${isCommitted ? "checked" : ""}`}
                role="checkbox"
                aria-checked={isCommitted}
                aria-label={`Commit to: ${rec.action}`}
                tabIndex={0}
                onKeyDown={(e) => {
                  if (e.key === " " || e.key === "Enter") {
                    e.preventDefault();
                    toggleCommit(i);
                  }
                }}
              >
                {isCommitted && <CheckIcon />}
              </div>
              <div className="recommendation-content">
                <span className="recommendation-category">{categoryLabel(rec.category)}</span>
                <span className="recommendation-text">{rec.action}</span>
                <div className="saving">
                  Potential saving: {formatKg(rec.estimated_annual_savings_kg)} CO₂e / year
                </div>
              </div>
            </li>
          );
        })}
      </ul>
    </section>
  );
}
